//! Embeds the Windows VERSIONINFO resource and the application icon into
//! Windows builds, so Explorer's Properties > Details shows the product
//! metadata. No-op for other targets.
//!
//! Also generates an `include_bytes!` table for the vendored EsMetrics UI
//! static assets (`assets/esmui/`, a rebranded upstream-vmui build),
//! written to `$OUT_DIR/esmui_assets.rs` and pulled in by `src/esmui.rs`
//! via `include!`. Generating the table here (rather than hand-listing
//! files) means adding/removing a vendored UI file only requires
//! re-running the build, not editing Rust source.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../assets/favicon.ico");

    generate_esmui_asset_table();

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let version = std::env::var("CARGO_PKG_VERSION").unwrap();
    // VERSIONINFO wants four 16-bit fields: 1.146.0 -> 1.146.0.0.
    let mut parts: Vec<u64> = version.split('.').map(|p| p.parse().unwrap_or(0)).collect();
    parts.resize(4, 0);
    let version_u64 = (parts[0] << 48) | (parts[1] << 32) | (parts[2] << 16) | parts[3];
    let version4 = format!("{}.{}.{}.{}", parts[0], parts[1], parts[2], parts[3]);

    let mut res = winresource::WindowsResource::new();
    res.set_icon("../../assets/favicon.ico")
        .set("ProductName", "EsMetrics")
        .set(
            "FileDescription",
            "EsMetrics - secure, fast, memory-safe time-series database",
        )
        .set("CompanyName", "Softalink LLC")
        .set("LegalCopyright", "Copyright © 2026 Softalink LLC")
        .set("OriginalFilename", "esmetrics.exe")
        .set("InternalName", "esmetrics")
        .set("ProductVersion", &version4)
        .set("FileVersion", &version4)
        .set_version_info(winresource::VersionInfo::PRODUCTVERSION, version_u64)
        .set_version_info(winresource::VersionInfo::FILEVERSION, version_u64)
        // 0x0409 = English (United States), the conventional neutral choice.
        .set_language(0x0409);

    if let Err(e) = res.compile() {
        panic!("failed to compile Windows resources: {e}");
    }
}

/// Walks `assets/esmui` and writes `$OUT_DIR/esmui_assets.rs`, a
/// `pub static ESMUI_ASSETS: &[(&str, &[u8])]` table mapping each file's
/// slash-separated logical path (relative to `assets/esmui`, e.g.
/// `"assets/index-abc123.js"`) to its bytes via `include_bytes!`.
///
/// Path handling is written to be safe on both Unix and Windows builds:
/// the logical keys always use `/` (they're URL path segments, not
/// filesystem paths), and the absolute filesystem path baked into each
/// `include_bytes!` literal is also normalized to `/` before being written
/// into the generated source, since the Windows file APIs Rust uses accept
/// `/` as a path separator just as readily as `\`. This avoids having to
/// escape backslashes when embedding a Windows path inside a string literal.
fn generate_esmui_asset_table() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let assets_root = Path::new(&manifest_dir).join("assets").join("esmui");
    println!("cargo:rerun-if-changed={}", assets_root.display());

    let mut files = Vec::new();
    if assets_root.is_dir() {
        collect_files(&assets_root, &assets_root, &mut files);
    }
    files.sort();
    // Fail at build time, not with a runtime panic on the first /esmui
    // request: the vendored assets are committed, so an empty table means
    // a broken checkout or a bad refactor of this script.
    assert!(
        files.iter().any(|(logical, _)| logical == "index.html"),
        "vendored esmui assets missing under {}: expected at least index.html",
        assets_root.display()
    );

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static ESMUI_ASSETS: &[(&str, &[u8])] = &[\n");
    for (logical, abs) in &files {
        out.push_str(&format!(
            "    ({logical:?}, include_bytes!({abs:?})),\n",
            logical = logical,
            abs = abs,
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("esmui_assets.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

/// Recursively collects `(logical_path, absolute_path)` pairs under `dir`.
/// `logical_path` is relative to `root`, always `/`-separated.
/// `absolute_path` is the file's full path, also `/`-separated (see
/// [`generate_esmui_asset_table`] for why that's safe on Windows too).
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let entries =
        fs::read_dir(dir).unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap_or_else(|e| panic!("failed to read entry: {e}"));
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out);
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .unwrap_or_else(|e| panic!("{} is not under {}: {e}", path.display(), root.display()));
        let logical = path_to_slash(rel);
        let abs = path_to_slash(&path);
        out.push((logical, abs));
    }
}

/// Renders a path with `/` separators regardless of the host OS (lossy for
/// the rare non-UTF-8 case). Deliberately a plain backslash replacement
/// rather than a `Path::components()` walk: on Unix, `RootDir` renders as
/// `/` in its own right, so rejoining components with `/` would double up
/// the leading slash on absolute paths (`//home/...`). A string replace
/// has no such edge case on either OS.
fn path_to_slash(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
