#!/usr/bin/env bash
# Produce a triage report of upstream changes since the recorded baseline.
#
# Usage:
#   scripts/upstream-diff.sh [NEW_VM_REF] [NEW_METRICSQL_REF]
#     NEW_VM_REF          VictoriaMetrics tag/commit to diff to (default:
#                         latest release tag)
#     NEW_METRICSQL_REF   metricsql tag/commit (default: latest tag)
#
# Reads baselines from ./UPSTREAM. Clones/fetches the upstream repos into
# .upstream/ (git-ignored; override location with UPSTREAM_CACHE=...).
# Writes the report to docs/sync/<baseline>..<new>.md and prints a summary.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
CACHE=${UPSTREAM_CACHE:-$ROOT/.upstream}
# shellcheck disable=SC1091
source <(grep -E '^[A-Z_]+=.*' "$ROOT/UPSTREAM" | sed 's/^\([A-Z_]*\)=\(.*\)$/\1="\2"/')

mkdir -p "$CACHE" "$ROOT/docs/sync"

fetch_repo() { # url dir
    if [ ! -d "$2/.git" ]; then
        git clone -q --filter=blob:none "$1" "$2"
    fi
    git -C "$2" fetch -q --tags origin
}

latest_tag() { # dir pattern — newest plain release tag (no -cluster/-rc/... suffixes)
    git -C "$1" tag -l "$2" --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1
}

fetch_repo "$VM_REPO" "$CACHE/VictoriaMetrics"
fetch_repo "$METRICSQL_REPO" "$CACHE/metricsql"

NEW_VM=${1:-$(latest_tag "$CACHE/VictoriaMetrics" 'v1.*')}
NEW_MQL=${2:-$(latest_tag "$CACHE/metricsql" 'v0.*')}

REPORT="$ROOT/docs/sync/${VM_TAG}..${NEW_VM}.md"
{
    echo "# Upstream sync triage: ${VM_TAG} -> ${NEW_VM}"
    echo
    echo "Generated by scripts/upstream-diff.sh on $(date -u +%F). Baselines"
    echo "from ./UPSTREAM. Triage each file below (adopt / adapt / skip) and"
    echo "record decisions in docs/UPSTREAM-SYNC.md."
    echo
    echo "## VictoriaMetrics ${VM_TAG} (${VM_COMMIT:0:12}) -> ${NEW_VM}"
    echo

    CHANGED=$(git -C "$CACHE/VictoriaMetrics" diff --name-only "$VM_COMMIT" "$NEW_VM" -- $VM_SCOPE || true)
    if [ -z "$CHANGED" ]; then
        echo "_No changes in ported scope._"
    else
        echo "| changed Go file | +/- | ported in (from provenance citations) |"
        echo "|---|---|---|"
        while IFS= read -r f; do
            STAT=$(git -C "$CACHE/VictoriaMetrics" diff --numstat "$VM_COMMIT" "$NEW_VM" -- "$f" | awk '{print "+"$1" -"$2}')
            RUST=$(python3 "$ROOT/scripts/upstream-map.py" --go-file "$f" 2>/dev/null | paste -sd' ' - || true)
            case "$f" in
                *_test.go) RUST="${RUST:-} (test file — port assertions alongside the fix)";;
            esac
            echo "| \`$f\` | $STAT | ${RUST:-**UNMAPPED — locate by hand**} |"
        done <<< "$CHANGED"
        echo
        echo "Full diff: \`git -C .upstream/VictoriaMetrics diff $VM_COMMIT $NEW_VM -- <file>\`"
    fi

    echo
    echo "## metricsql ${METRICSQL_TAG} (${METRICSQL_COMMIT:0:12}) -> ${NEW_MQL}"
    echo
    MQL_CHANGED=$(git -C "$CACHE/metricsql" diff --name-only "$METRICSQL_COMMIT" "$NEW_MQL" -- '*.go' || true)
    if [ -z "$MQL_CHANGED" ]; then
        echo "_No changes._"
    else
        echo '```'
        git -C "$CACHE/metricsql" diff --stat "$METRICSQL_COMMIT" "$NEW_MQL" -- '*.go'
        echo '```'
        echo
        echo "All metricsql changes map to \`crates/esm-metricsql\`."
    fi

    echo
    echo "## Out-of-scope changes (informational count)"
    TOTAL=$(git -C "$CACHE/VictoriaMetrics" diff --name-only "$VM_COMMIT" "$NEW_VM" | wc -l)
    IN=$(printf '%s' "$CHANGED" | grep -c . || true)
    echo
    echo "$IN of $TOTAL changed files are in ported scope."
} > "$REPORT"

echo "report: ${REPORT#"$ROOT"/}"
grep -cE '^\| `' "$REPORT" | xargs -I{} echo "files to triage: {}"
