//! Port of the upstream VictoriaMetrics `lib/uint64set` (v1.146.0).
//!
//! A fast set for `u64` values, optimized for semi-sparse values such as
//! MetricIDs generated by the storage layer. The set is organized as a
//! hierarchy: [`Set`] holds `Bucket32` entries keyed by the high 32 bits,
//! each `Bucket32` holds `Bucket16` entries keyed by the next 16 bits, and
//! each `Bucket16` stores the low 16 bits either in a small sorted-on-demand
//! pool (up to 56 items) or in a 64-Kbit bitmap.
//!
//! Deviations from the Go original:
//! - Go uses `atomic` load/store for the per-`bucket32` `hint` field so that
//!   concurrent read-mostly usage is race-free. Rust ownership makes this
//!   unnecessary: all mutating methods take `&mut self`, so `hint` is a plain
//!   `u32`.
//! - `UnionMayOwn` in Go may share (own) `a`'s buckets when profitable.
//!   With Rust ownership there is no benefit to sharing, so
//!   [`Set::union_may_own`] delegates to [`Set::union`]; observable behavior
//!   is identical (and `a` remains usable, unlike in Go).
//! - Go's `Clone` relies on copy semantics of slices plus explicit `copyTo`;
//!   the Rust port implements [`Clone`] with the same deep-copy semantics.
//! - Go pools iteration buffers in a `sync.Pool`; the Rust port allocates a
//!   per-call buffer in [`Set::for_each`] instead.
//! - `SizeBytes` uses `std::mem::size_of` instead of `unsafe.Sizeof`. The
//!   accounting structure mirrors Go's (struct size + 2 bytes per `b16his`
//!   entry + per-`bucket16` size + optional bitmap size), but the exact
//!   numbers differ from Go since struct layouts differ (e.g. Go's `Set`
//!   embeds a scratch bucket).
//! - `Subtract`'s "s is smaller" branch in Go deletes from `s` while
//!   iterating it via `ForEach`; the Rust port first collects the items to
//!   delete, then deletes them. The result is identical.

const BITS_PER_BUCKET: usize = 1 << 16;
const WORDS_PER_BUCKET: usize = BITS_PER_BUCKET / 64;
const SMALL_POOL_SIZE: usize = 56;

/// Port of Go `uint64set.Set` - a fast set for `u64`.
///
/// It should work faster than `HashSet<u64>` for semi-sparse `u64` values
/// such as MetricIDs generated by the storage layer.
#[derive(Default)]
pub struct Set {
    items_count: usize,
    buckets: Vec<Bucket32>,
}

impl Clone for Set {
    /// Port of Go `uint64set.Set.Clone` - returns an independent copy.
    fn clone(&self) -> Self {
        if self.items_count == 0 {
            // Return an empty set, so data could be added into it later.
            return Set::default();
        }
        Set {
            items_count: self.items_count,
            buckets: self.buckets.clone(),
        }
    }
}

impl Set {
    /// Port of Go `uint64set.Unmarshal` - creates a set from bytes.
    ///
    /// The first 8 src bytes contain the set length (number of the elements
    /// in the set), big-endian. The function reads exactly `8*length`
    /// subsequent bytes and constructs the set. The remaining src bytes are
    /// returned along with the set.
    pub fn unmarshal(src: &[u8]) -> Result<(Set, &[u8]), String> {
        if src.len() < 8 {
            return Err(format!(
                "cannot unmarshal uint64set; got {} bytes; want at least 8 bytes",
                src.len()
            ));
        }
        let s_len = read_u64_be(src);
        let mut src = &src[8..];
        if (src.len() as u64) / 8 < s_len {
            return Err(format!(
                "cannot unmarshal uint64set; got {} bytes; want at least {} bytes",
                src.len(),
                8 * s_len
            ));
        }
        let mut s = Set::default();
        for _ in 0..s_len {
            let e = read_u64_be(src);
            src = &src[8..];
            s.add(e);
        }
        Ok((s, src))
    }

    /// Port of Go `uint64set.Set.Marshal` - encodes the set as bytes.
    ///
    /// The first 8 bytes contain the length of the set, big-endian. The
    /// subsequent bytes are the `u64` elements. The result is appended to
    /// `dst`, i.e. the initial `dst` content is not overwritten.
    pub fn marshal(&self, mut dst: Vec<u8>) -> Vec<u8> {
        dst.extend_from_slice(&(self.len() as u64).to_be_bytes());
        self.for_each(|part| {
            for &e in part {
                dst.extend_from_slice(&e.to_be_bytes());
            }
            true
        });
        dst
    }

    fn fix_items_count(&mut self) {
        let mut n = 0;
        for b32 in &self.buckets {
            n += b32.get_len();
        }
        self.items_count = n;
    }

    /// Port of Go `uint64set.Set.SizeBytes` - an estimate of the set size in RAM.
    ///
    /// Uses `std::mem::size_of` in place of Go's `unsafe.Sizeof`; the
    /// accounting structure mirrors Go's, the exact numbers do not.
    pub fn size_bytes(&self) -> u64 {
        let mut n = std::mem::size_of::<Set>() as u64;
        for b32 in &self.buckets {
            n += b32.size_bytes();
        }
        n
    }

    /// Port of Go `uint64set.Set.Len` - the number of distinct values in the set.
    pub fn len(&self) -> usize {
        self.items_count
    }

    /// Returns true if the set contains no items. (No direct Go counterpart;
    /// required by Rust API conventions alongside `len`.)
    pub fn is_empty(&self) -> bool {
        self.items_count == 0
    }

    /// Port of Go `uint64set.Set.Add` - adds `x` to the set.
    pub fn add(&mut self, x: u64) {
        let hi32 = (x >> 32) as u32;
        let lo32 = x as u32;
        if let Some(first) = self.buckets.first_mut() {
            if first.hi == hi32 {
                // Manually inlined bucket32.add fast path, as in Go.
                let hi16 = (lo32 >> 16) as u16;
                let lo16 = lo32 as u16;
                let n = first.hint as usize;
                let added = if n < first.b16his.len() && first.b16his[n] == hi16 {
                    n < first.buckets.len() && first.buckets[n].add(lo16)
                } else {
                    first.add_slow(hi16, lo16)
                };
                if added {
                    self.items_count += 1;
                }
                return;
            }
        }
        for b32 in &mut self.buckets {
            if b32.hi == hi32 {
                if b32.add(lo32) {
                    self.items_count += 1;
                }
                return;
            }
        }
        let b32 = self.add_bucket32();
        b32.hi = hi32;
        b32.add(lo32);
        self.items_count += 1;
    }

    /// Port of Go `uint64set.Set.AddMulti` - adds all the items from `a`.
    ///
    /// It is usually faster than calling [`Set::add`] for each item in `a`.
    /// The caller is responsible for splitting `a` into items with clustered
    /// values.
    pub fn add_multi(&mut self, a: &[u64]) {
        if a.is_empty() {
            return;
        }
        let mut hi_prev = (a[0] >> 32) as u32;
        let mut i = 0;
        for (j, &x) in a.iter().enumerate() {
            let hi = (x >> 32) as u32;
            if hi == hi_prev {
                continue;
            }
            let count = self.get_or_create_bucket32(hi_prev).add_multi(&a[i..j]);
            self.items_count += count;
            hi_prev = hi;
            i = j;
        }
        let count = self.get_or_create_bucket32(hi_prev).add_multi(&a[i..]);
        self.items_count += count;
    }

    fn get_or_create_bucket32(&mut self, hi: u32) -> &mut Bucket32 {
        if let Some(pos) = self.buckets.iter().position(|b| b.hi == hi) {
            return &mut self.buckets[pos];
        }
        let b32 = self.add_bucket32();
        b32.hi = hi;
        b32
    }

    fn add_bucket32(&mut self) -> &mut Bucket32 {
        self.buckets.push(Bucket32::default());
        let idx = self.buckets.len() - 1;
        &mut self.buckets[idx]
    }

    /// Port of Go `uint64set.Set.Has` - verifies whether `x` exists in the set.
    pub fn has(&self, x: u64) -> bool {
        let hi32 = (x >> 32) as u32;
        let lo32 = x as u32;
        for b32 in &self.buckets {
            if b32.hi == hi32 {
                return b32.has(lo32);
            }
        }
        false
    }

    /// Port of Go `uint64set.Set.Del` - deletes `x` from the set.
    pub fn del(&mut self, x: u64) {
        let hi = (x >> 32) as u32;
        let lo = x as u32;
        if let Some(first) = self.buckets.first_mut() {
            if first.hi == hi {
                if first.del(lo) {
                    self.items_count -= 1;
                }
                return;
            }
        }
        for b32 in &mut self.buckets {
            if b32.hi == hi {
                if b32.del(lo) {
                    self.items_count -= 1;
                }
                return;
            }
        }
    }

    /// Port of Go `uint64set.Set.AppendTo` - appends all the items to `dst`
    /// and returns the result.
    ///
    /// The returned items are sorted. As in Go, `append_to` can mutate the
    /// set (it sorts the internal buckets), hence `&mut self`.
    pub fn append_to(&mut self, mut dst: Vec<u64>) -> Vec<u64> {
        // Pre-allocate memory for dst.
        dst.reserve(self.len());
        self.sort();
        for b32 in &self.buckets {
            b32.append_to(&mut dst);
        }
        dst
    }

    fn sort(&mut self) {
        // Sort the buckets if they aren't sorted yet.
        if !self.buckets.is_sorted_by_key(|b| b.hi) {
            self.buckets.sort_by_key(|b| b.hi);
        }
    }

    /// Port of Go `uint64set.Set.Union` - adds all the items from `a` to the set.
    pub fn union(&mut self, a: &Set) {
        self.union_internal(a);
    }

    /// Port of Go `uint64set.Set.UnionMayOwn` - adds all the items from `a`.
    ///
    /// In Go this may take ownership of `a`'s buckets as an optimization;
    /// Rust ownership makes that moot, so this delegates to [`Set::union`]
    /// (and, unlike in Go, `a` remains fully usable afterwards).
    pub fn union_may_own(&mut self, a: &Set) {
        self.union_internal(a);
    }

    fn union_internal(&mut self, a: &Set) {
        if a.is_empty() {
            // Fast path - nothing to union.
            return;
        }
        if self.is_empty() {
            // Fast path - copy `a` to `self`.
            *self = a.clone();
            return;
        }
        // Iterate `a`'s buckets in sorted order via an index permutation.
        // (Go makes a shallow clone of `a` and sorts it; `&Set` forbids that.)
        let order = sorted_bucket_order(a);
        self.sort();
        let mut i = 0;
        let mut j = 0;
        let s_buckets_len = self.buckets.len();
        loop {
            while i < s_buckets_len
                && j < order.len()
                && self.buckets[i].hi < a.buckets[order[j]].hi
            {
                i += 1;
            }
            if i >= s_buckets_len {
                while j < order.len() {
                    self.buckets.push(a.buckets[order[j]].clone());
                    j += 1;
                }
                break;
            }
            while j < order.len() && a.buckets[order[j]].hi < self.buckets[i].hi {
                self.buckets.push(a.buckets[order[j]].clone());
                j += 1;
            }
            if j >= order.len() {
                break;
            }
            if self.buckets[i].hi == a.buckets[order[j]].hi {
                self.buckets[i].union(&a.buckets[order[j]]);
                i += 1;
                j += 1;
            }
        }
        self.fix_items_count();
    }

    /// Port of Go `uint64set.Set.Intersect` - removes all the items missing
    /// in `a` from the set.
    pub fn intersect(&mut self, a: &Set) {
        if self.is_empty() || a.is_empty() {
            // Fast path - the result is empty.
            *self = Set::default();
            return;
        }
        // Iterate `a`'s buckets in sorted order via an index permutation.
        let order = sorted_bucket_order(a);
        self.sort();
        let mut i = 0;
        let mut j = 0;
        loop {
            while i < self.buckets.len()
                && j < order.len()
                && self.buckets[i].hi < a.buckets[order[j]].hi
            {
                self.buckets[i] = Bucket32::default();
                i += 1;
            }
            if i >= self.buckets.len() {
                break;
            }
            while j < order.len() && a.buckets[order[j]].hi < self.buckets[i].hi {
                j += 1;
            }
            if j >= order.len() {
                while i < self.buckets.len() {
                    self.buckets[i] = Bucket32::default();
                    i += 1;
                }
                break;
            }
            if self.buckets[i].hi == a.buckets[order[j]].hi {
                self.buckets[i].intersect(&a.buckets[order[j]]);
                i += 1;
                j += 1;
            }
        }
        self.fix_items_count();
    }

    /// Port of Go `uint64set.Set.Subtract` - removes from the set all the
    /// items shared between it and `a`.
    pub fn subtract(&mut self, a: &Set) {
        if self.is_empty() || a.is_empty() {
            // Fast path - nothing to subtract.
            return;
        }
        if self.len() >= a.len() {
            a.for_each(|part| {
                for &x in part {
                    self.del(x);
                }
                true
            });
        } else {
            // Go deletes from `s` while iterating it via ForEach; Rust
            // ownership forbids that, so collect the doomed items first.
            let mut to_del = Vec::new();
            self.for_each(|part| {
                for &x in part {
                    if a.has(x) {
                        to_del.push(x);
                    }
                }
                true
            });
            for x in to_del {
                self.del(x);
            }
        }
    }

    /// Port of Go `uint64set.Set.Equal` - returns true if the set contains
    /// the same items as `a`.
    pub fn equal(&self, a: &Set) -> bool {
        if self.len() != a.len() {
            return false;
        }
        let mut equal = true;
        a.for_each(|part| {
            for &x in part {
                if !self.has(x) {
                    equal = false;
                    return false;
                }
            }
            true
        });
        equal
    }

    /// Port of Go `uint64set.Set.ForEach` - calls `f` for all the items
    /// stored in the set.
    ///
    /// Each call to `f` receives an arbitrary part of the items stored in
    /// the set. The iteration is stopped if `f` returns false.
    pub fn for_each<F: FnMut(&[u64]) -> bool>(&self, mut f: F) {
        // Go pools this buffer in a sync.Pool; here it is a per-call buffer.
        let mut buf: Vec<u64> = Vec::new();
        for b32 in &self.buckets {
            if !b32.for_each(&mut f, &mut buf) {
                return;
            }
        }
    }
}

/// Returns the indexes of `a.buckets` in ascending `hi` order.
fn sorted_bucket_order(a: &Set) -> Vec<usize> {
    let mut order: Vec<usize> = (0..a.buckets.len()).collect();
    order.sort_by_key(|&k| a.buckets[k].hi);
    order
}

fn read_u64_be(src: &[u8]) -> u64 {
    let mut b = [0u8; 8];
    b.copy_from_slice(&src[..8]);
    u64::from_be_bytes(b)
}

/// Port of Go `uint64set.bucket32`.
#[derive(Default)]
struct Bucket32 {
    hi: u32,

    // hint may contain the bucket index of the last successful operation.
    // This allows saving CPU time on subsequent calls to the same bucket.
    // Go stores it atomically for lock-free concurrent reads; `&mut self`
    // discipline makes a plain field sufficient here.
    hint: u32,

    // b16his contains the high 16 bits for each bucket in `buckets`.
    //
    // It is always sorted.
    b16his: Vec<u16>,

    // buckets are sorted by b16his.
    buckets: Vec<Bucket16>,
}

impl Clone for Bucket32 {
    // Mirrors Go bucket32.copyTo: the hint is not copied.
    fn clone(&self) -> Self {
        Bucket32 {
            hi: self.hi,
            hint: 0,
            b16his: self.b16his.clone(),
            buckets: self.buckets.clone(),
        }
    }
}

impl Bucket32 {
    fn get_len(&self) -> usize {
        let mut n = 0;
        for b16 in &self.buckets {
            n += b16.get_len();
        }
        n
    }

    fn union(&mut self, a: &Bucket32) {
        let mut i = 0;
        let mut j = 0;
        let b_buckets_len = self.buckets.len();
        loop {
            while i < b_buckets_len && j < a.b16his.len() && self.b16his[i] < a.b16his[j] {
                i += 1;
            }
            if i >= b_buckets_len {
                while j < a.b16his.len() {
                    self.b16his.push(a.b16his[j]);
                    self.buckets.push(a.buckets[j].clone());
                    j += 1;
                }
                break;
            }
            while j < a.b16his.len() && a.b16his[j] < self.b16his[i] {
                self.b16his.push(a.b16his[j]);
                self.buckets.push(a.buckets[j].clone());
                j += 1;
            }
            if j >= a.b16his.len() {
                break;
            }
            if self.b16his[i] == a.b16his[j] {
                self.buckets[i].union(&a.buckets[j]);
                i += 1;
                j += 1;
            }
        }
        // Restore the bucket order, which could be violated during the merge above.
        if !self.b16his.is_sorted() {
            let mut pairs: Vec<(u16, Bucket16)> =
                self.b16his.drain(..).zip(self.buckets.drain(..)).collect();
            pairs.sort_by_key(|p| p.0);
            for (hi, b16) in pairs {
                self.b16his.push(hi);
                self.buckets.push(b16);
            }
        }
    }

    fn intersect(&mut self, a: &Bucket32) {
        let mut i = 0;
        let mut j = 0;
        loop {
            while i < self.b16his.len() && j < a.b16his.len() && self.b16his[i] < a.b16his[j] {
                self.buckets[i] = Bucket16::default();
                i += 1;
            }
            if i >= self.b16his.len() {
                break;
            }
            while j < a.b16his.len() && a.b16his[j] < self.b16his[i] {
                j += 1;
            }
            if j >= a.b16his.len() {
                while i < self.b16his.len() {
                    self.buckets[i] = Bucket16::default();
                    i += 1;
                }
                break;
            }
            if self.b16his[i] == a.b16his[j] {
                self.buckets[i].intersect(&a.buckets[j]);
                i += 1;
                j += 1;
            }
        }
        // Remove zero buckets.
        let his = std::mem::take(&mut self.b16his);
        let bs = std::mem::take(&mut self.buckets);
        for (hi, b16) in his.into_iter().zip(bs) {
            if b16.is_zero() {
                continue;
            }
            self.b16his.push(hi);
            self.buckets.push(b16);
        }
        self.hint = 0;
    }

    fn for_each<F: FnMut(&[u64]) -> bool>(&self, f: &mut F, buf: &mut Vec<u64>) -> bool {
        for (i, b16) in self.buckets.iter().enumerate() {
            let hi16 = self.b16his[i];
            buf.clear();
            b16.append_to(buf, self.hi, hi16);
            if !f(buf) {
                return false;
            }
        }
        true
    }

    fn size_bytes(&self) -> u64 {
        let mut n = std::mem::size_of::<Bucket32>() as u64;
        n += 2 * self.b16his.len() as u64;
        for b16 in &self.buckets {
            n += b16.size_bytes();
        }
        n
    }

    fn add(&mut self, x: u32) -> bool {
        let hi = (x >> 16) as u16;
        let lo = x as u16;
        let n = self.hint as usize;
        if n < self.b16his.len() && self.b16his[n] == hi {
            // Fast path - add to the previously used bucket.
            return n < self.buckets.len() && self.buckets[n].add(lo);
        }
        self.add_slow(hi, lo)
    }

    fn add_multi(&mut self, a: &[u64]) -> usize {
        if a.is_empty() {
            return 0;
        }
        let mut count = 0;
        let mut hi_prev = (a[0] >> 16) as u16;
        let mut i = 0;
        for (j, &x) in a.iter().enumerate() {
            let hi = (x >> 16) as u16;
            if hi == hi_prev {
                continue;
            }
            count += self.get_or_create_bucket16(hi_prev).add_multi(&a[i..j]);
            hi_prev = hi;
            i = j;
        }
        count += self.get_or_create_bucket16(hi_prev).add_multi(&a[i..]);
        count
    }

    fn get_or_create_bucket16(&mut self, hi: u16) -> &mut Bucket16 {
        let n = binary_search16(&self.b16his, hi);
        if n >= self.b16his.len() || self.b16his[n] != hi {
            return self.add_bucket_at_pos(hi, n);
        }
        &mut self.buckets[n]
    }

    fn add_slow(&mut self, hi: u16, lo: u16) -> bool {
        let n = binary_search16(&self.b16his, hi);
        if n >= self.b16his.len() || self.b16his[n] != hi {
            let b16 = self.add_bucket_at_pos(hi, n);
            b16.add(lo);
            return true;
        }
        self.hint = n as u32;
        n < self.buckets.len() && self.buckets[n].add(lo)
    }

    fn add_bucket_at_pos(&mut self, hi: u16, pos: usize) -> &mut Bucket16 {
        if pos >= self.b16his.len() {
            self.b16his.push(hi);
            self.buckets.push(Bucket16::default());
            let idx = self.buckets.len() - 1;
            return &mut self.buckets[idx];
        }
        self.b16his.insert(pos, hi);
        self.buckets.insert(pos, Bucket16::default());
        &mut self.buckets[pos]
    }

    fn has(&self, x: u32) -> bool {
        let hi = (x >> 16) as u16;
        let lo = x as u16;
        let n = binary_search16(&self.b16his, hi);
        if n >= self.b16his.len() || self.b16his[n] != hi {
            return false;
        }
        // Do not update the hint here, mirroring Go (which avoids it to keep
        // concurrent readers fast).
        n < self.buckets.len() && self.buckets[n].has(lo)
    }

    fn del(&mut self, x: u32) -> bool {
        let hi = (x >> 16) as u16;
        let lo = x as u16;
        let n = self.hint as usize;
        if n < self.b16his.len() && self.b16his[n] == hi {
            // Fast path - use the bucket from the previous operation.
            return n < self.buckets.len() && self.buckets[n].del(lo);
        }
        self.del_slow(hi, lo)
    }

    fn del_slow(&mut self, hi: u16, lo: u16) -> bool {
        let n = binary_search16(&self.b16his, hi);
        if n >= self.b16his.len() || self.b16his[n] != hi {
            return false;
        }
        self.hint = n as u32;
        n < self.buckets.len() && self.buckets[n].del(lo)
    }

    fn append_to(&self, dst: &mut Vec<u64>) {
        for (i, b16) in self.buckets.iter().enumerate() {
            let hi16 = self.b16his[i];
            b16.append_to(dst, self.hi, hi16);
        }
    }
}

/// Port of Go `uint64set.bucket16`.
#[derive(Clone)]
struct Bucket16 {
    bits: Option<Box<[u64; WORDS_PER_BUCKET]>>,
    small_pool: [u16; SMALL_POOL_SIZE],
    small_pool_len: usize,
}

impl Default for Bucket16 {
    fn default() -> Self {
        Bucket16 {
            bits: None,
            small_pool: [0; SMALL_POOL_SIZE],
            small_pool_len: 0,
        }
    }
}

impl Bucket16 {
    fn is_zero(&self) -> bool {
        self.bits.is_none() && self.small_pool_len == 0
    }

    fn get_len(&self) -> usize {
        match &self.bits {
            None => self.small_pool_len,
            Some(bits) => {
                let mut n = 0;
                for &x in bits.iter() {
                    if x > 0 {
                        n += x.count_ones() as usize;
                    }
                }
                n
            }
        }
    }

    fn union(&mut self, a: &Bucket16) {
        if let Some(ab) = &a.bits {
            if let Some(bb) = &mut self.bits {
                // Fast path - use bitwise ops.
                for (bx, &ax) in bb.iter_mut().zip(ab.iter()) {
                    *bx |= ax;
                }
                return;
            }
        }

        // Slow path.
        let mut buf = Vec::new();
        a.append_to(&mut buf, 0, 0);
        for &x in &buf {
            self.add(x as u16);
        }
    }

    fn intersect(&mut self, a: &Bucket16) {
        if let Some(ab) = &a.bits {
            if let Some(bb) = &mut self.bits {
                // Fast path - use bitwise ops.
                for (bx, &ax) in bb.iter_mut().zip(ab.iter()) {
                    *bx &= ax;
                }
                return;
            }
        }

        // Slow path.
        let mut buf = Vec::new();
        self.append_to(&mut buf, 0, 0);
        for &x in &buf {
            let x16 = x as u16;
            if !a.has(x16) {
                self.del(x16);
            }
        }
    }

    fn size_bytes(&self) -> u64 {
        let mut n = std::mem::size_of::<Bucket16>();
        if self.bits.is_some() {
            n += std::mem::size_of::<[u64; WORDS_PER_BUCKET]>();
        }
        n as u64
    }

    fn add(&mut self, x: u16) -> bool {
        match &mut self.bits {
            None => self.add_to_small_pool(x),
            Some(bits) => {
                let (word_num, bit_mask) = get_word_num_bit_mask(x);
                let ok = bits[word_num] & bit_mask == 0;
                if ok {
                    bits[word_num] |= bit_mask;
                }
                ok
            }
        }
    }

    fn add_multi(&mut self, a: &[u64]) -> usize {
        if self.bits.is_none() {
            if self.small_pool_len + a.len() <= SMALL_POOL_SIZE {
                // Slow path.
                let mut count = 0;
                for &x in a {
                    if self.add_to_small_pool(x as u16) {
                        count += 1;
                    }
                }
                return count;
            }
            self.switch_small_pool_to_bits();
        }

        // Fast path.
        let Some(bits) = self.bits.as_deref_mut() else {
            return 0; // unreachable: bits is always Some here
        };
        let mut count = 0;
        for &x in a {
            let (word_num, bit_mask) = get_word_num_bit_mask(x as u16);
            if bits[word_num] & bit_mask == 0 {
                bits[word_num] |= bit_mask;
                count += 1;
            }
        }
        count
    }

    fn add_to_small_pool(&mut self, x: u16) -> bool {
        if self.has_in_small_pool(x) {
            return false;
        }
        if self.small_pool_len < SMALL_POOL_SIZE {
            self.small_pool[self.small_pool_len] = x;
            self.small_pool_len += 1;
            return true;
        }
        self.switch_small_pool_to_bits();
        self.add(x);
        true
    }

    fn switch_small_pool_to_bits(&mut self) {
        let small_pool_len = self.small_pool_len;
        self.small_pool_len = 0;
        self.bits = Some(Box::new([0u64; WORDS_PER_BUCKET]));
        let pool = self.small_pool;
        for &v in &pool[..small_pool_len] {
            self.add(v);
        }
    }

    fn has(&self, x: u16) -> bool {
        match &self.bits {
            None => self.has_in_small_pool(x),
            Some(bits) => {
                let (word_num, bit_mask) = get_word_num_bit_mask(x);
                bits[word_num] & bit_mask != 0
            }
        }
    }

    fn has_in_small_pool(&self, x: u16) -> bool {
        self.small_pool[..self.small_pool_len].contains(&x)
    }

    fn del(&mut self, x: u16) -> bool {
        match &mut self.bits {
            None => self.del_from_small_pool(x),
            Some(bits) => {
                let (word_num, bit_mask) = get_word_num_bit_mask(x);
                let word = &mut bits[word_num];
                let ok = *word & bit_mask != 0;
                *word &= !bit_mask;
                ok
            }
        }
    }

    fn del_from_small_pool(&mut self, x: u16) -> bool {
        if let Some(i) = self.small_pool[..self.small_pool_len]
            .iter()
            .position(|&v| v == x)
        {
            self.small_pool.copy_within(i + 1..self.small_pool_len, i);
            self.small_pool_len -= 1;
            return true;
        }
        false
    }

    fn append_to(&self, dst: &mut Vec<u64>, hi: u32, hi16: u16) {
        let hi64 = (hi as u64) << 32 | (hi16 as u64) << 16;
        match &self.bits {
            None => {
                // Sort a copy of the small pool, since `self` must stay
                // readonly (mirrors Go, which sorts a copy to avoid data
                // races between concurrent readers).
                let mut pool = self.small_pool;
                let a = &mut pool[..self.small_pool_len];
                if a.len() > 1 && !a.is_sorted() {
                    a.sort_unstable();
                }
                for &v in a.iter() {
                    dst.push(hi64 | v as u64);
                }
            }
            Some(bits) => {
                let mut word_num: u64 = 0;
                for &w in bits.iter() {
                    if w == 0 {
                        word_num += 1;
                        continue;
                    }
                    let mut word = w;
                    let x64 = hi64 | (word_num * 64);
                    loop {
                        let tzn = word.trailing_zeros() as u64;
                        if tzn >= 64 {
                            break;
                        }
                        word &= !(1u64 << tzn);
                        dst.push(x64 | tzn);
                    }
                    word_num += 1;
                }
            }
        }
    }
}

fn get_word_num_bit_mask(x: u16) -> (usize, u64) {
    let word_num = (x / 64) as usize;
    let bit_mask = 1u64 << (x & 63);
    (word_num, bit_mask)
}

// Port of Go `uint64set.binarySearch16`, including the fast path for values
// scanned in ascending order.
fn binary_search16(u16s: &[u16], x: u16) -> usize {
    let n = u16s.len();
    if n > 0 && u16s[n - 1] < x {
        // Fast path for values scanned in ascending order.
        return n;
    }
    let mut i = 0;
    let mut j = n;
    while i < j {
        let h = (i + j) >> 1;
        if u16s[h] < x {
            i = h + 1;
        } else {
            j = h;
        }
    }
    i
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::StdRng;
    use rand::{Rng, SeedableRng};
    use std::collections::HashSet;
    use std::time::{SystemTime, UNIX_EPOCH};

    // Port of Go TestSetOps.
    #[test]
    fn test_set_ops() {
        let f = |a: &[u64], b: &[u64]| check_set_ops(a, b);

        f(&[], &[]);
        f(&[1], &[]);
        f(&[1, 2, 3], &[]);
        f(&[1, 2, 3, 1 << 16, 1 << 32, 2 << 32], &[]);
        f(&[1], &[1]);
        f(&[0], &[1 << 16]);
        f(&[1], &[1 << 16]);
        f(&[1], &[4 << 16]);
        f(&[1], &[1 << 32]);
        f(&[1], &[1 << 32, 2 << 32]);
        f(&[1], &[2 << 32]);
        f(&[1, (1 << 16) - 1], &[1 << 16]);
        f(&[0, (1 << 16) - 1], &[1 << 16, (1 << 16) - 1]);
        f(
            &[0, (1 << 16) - 1],
            &[1 << 16, (1 << 16) - 1, 2 << 16, 8 << 16],
        );
        f(&[0], &[1 << 16, (1 << 16) - 1, 2 << 16, 8 << 16]);
        f(&[0, 2 << 16], &[1 << 16]);
        f(&[0, 2 << 16], &[1 << 16, 3 << 16]);
        f(&[0, 2 << 16], &[1 << 16, 2 << 16]);
        f(&[0, 2 << 16], &[1 << 16, 2 << 16, 3 << 16]);
        f(&[0, 2 << 32], &[1 << 32]);
        f(&[0, 2 << 32], &[1 << 32, 3 << 32]);
        f(&[0, 2 << 32], &[1 << 32, 2 << 32]);
        f(&[0, 2 << 32], &[1 << 32, 2 << 32, 3 << 32]);

        let mut a: Vec<u64> = Vec::new();
        for i in 0..100u64 {
            a.push(i);
        }
        let mut b: Vec<u64> = Vec::new();
        for i in (1u64 << 16)..(1 << 16) + 1000 {
            b.push(i);
        }
        f(&a, &b);

        for i in (1u64 << 16) - 100..(1 << 16) + 100 {
            a.push(i);
        }
        for i in (1u64 << 32)..(1 << 32) + (1 << 16) + 200 {
            b.push(i);
        }
        f(&a, &b);

        let mut rng = StdRng::seed_from_u64(1);
        for _ in 0..10 {
            a.clear();
            b.clear();
            for _ in 0..1000 {
                a.push(rng.random_range(0..1_000_000u64));
                b.push(rng.random_range(0..1_000_000u64));
            }
            f(&a, &b);
        }
    }

    fn check_set_ops(a: &[u64], b: &[u64]) {
        let mut m_union: HashSet<u64> = HashSet::new();
        let mut m_intersect: HashSet<u64> = HashSet::new();
        let mut ma: HashSet<u64> = HashSet::new();
        let mut sa = Set::default();
        let mut sb = Set::default();
        for &v in a {
            sa.add(v);
            ma.insert(v);
            m_union.insert(v);
        }
        for &v in b {
            sb.add(v);
            m_union.insert(v);
            if ma.contains(&v) {
                m_intersect.insert(v);
            }
        }
        let sa_orig = sa.clone();
        assert!(sa_orig.equal(&sa), "saOrig must be equal to sa");
        let sb_orig = sb.clone();
        assert!(sb_orig.equal(&sb), "sbOrig must be equal to sb");

        // Verify sa.union(sb)
        sa.union(&sb);
        if let Err(err) = expect_equal(&mut sa, &m_union) {
            panic!("invalid sa.union(sb): {err}");
        }
        assert!(
            sb_orig.equal(&sb),
            "sbOrig must be equal to sb after sa.union(sb)"
        );

        // Verify sb.union(sa)
        let sa = sa_orig.clone();
        sb.union(&sa);
        if let Err(err) = expect_equal(&mut sb, &m_union) {
            panic!("invalid sb.union(sa): {err}");
        }
        assert!(
            sa_orig.equal(&sa),
            "saOrig must be equal to sa after sb.union(sa)"
        );

        // Verify sa.union_may_own(sb)
        let mut sa = sa_orig.clone();
        let mut sb = sb_orig.clone();
        sa.union_may_own(&sb);
        if let Err(err) = expect_equal(&mut sa, &m_union) {
            panic!("invalid sa.union_may_own(sb): {err}");
        }
        assert!(
            sb_orig.equal(&sb),
            "sbOrig must be equal to sb after sa.union_may_own(sb)"
        );

        // Verify sb.union_may_own(sa)
        let sa = sa_orig.clone();
        sb.union_may_own(&sa);
        if let Err(err) = expect_equal(&mut sb, &m_union) {
            panic!("invalid sb.union_may_own(sa): {err}");
        }
        assert!(
            sa_orig.equal(&sa),
            "saOrig must be equal to sa after sb.union_may_own(sa)"
        );

        // Verify sa.intersect(sb)
        let mut sa = sa_orig.clone();
        let mut sb = sb_orig.clone();
        sa.intersect(&sb);
        if let Err(err) = expect_equal(&mut sa, &m_intersect) {
            panic!("invalid sa.intersect(sb): {err}");
        }
        assert!(
            sb_orig.equal(&sb),
            "sbOrig must be equal to sb after sa.intersect(sb)"
        );

        // Verify sb.intersect(sa)
        let sa = sa_orig.clone();
        sb.intersect(&sa);
        if let Err(err) = expect_equal(&mut sb, &m_intersect) {
            panic!("invalid sb.intersect(sa): {err}");
        }
        assert!(
            sa_orig.equal(&sa),
            "saOrig must be equal to sa after sb.intersect(sa)"
        );

        // Verify sa.subtract(sb)
        let mut m_subtract_ab: HashSet<u64> = HashSet::new();
        for &v in a {
            m_subtract_ab.insert(v);
        }
        for &v in b {
            m_subtract_ab.remove(&v);
        }
        let mut sa = sa_orig.clone();
        let mut sb = sb_orig.clone();
        sa.subtract(&sb);
        if let Err(err) = expect_equal(&mut sa, &m_subtract_ab) {
            panic!("invalid sa.subtract(sb): {err}");
        }
        assert!(
            sb_orig.equal(&sb),
            "sbOrig must be equal to sb after sa.subtract(sb)"
        );

        // Verify sb.subtract(sa)
        let mut m_subtract_ba: HashSet<u64> = HashSet::new();
        for &v in b {
            m_subtract_ba.insert(v);
        }
        for &v in a {
            m_subtract_ba.remove(&v);
        }
        let sa = sa_orig.clone();
        sb.subtract(&sa);
        if let Err(err) = expect_equal(&mut sb, &m_subtract_ba) {
            panic!("invalid sb.subtract(sa): {err}");
        }
        assert!(
            sa_orig.equal(&sa),
            "saOrig must be equal to sa after sb.subtract(sa)"
        );
    }

    // Port of Go expectEqual.
    fn expect_equal(s: &mut Set, m: &HashSet<u64>) -> Result<(), String> {
        if s.len() != m.len() {
            return Err(format!(
                "unexpected s.len(); got {}; want {}\ns={:?}\nm={:?}",
                s.len(),
                m.len(),
                s.append_to(Vec::new()),
                m
            ));
        }
        for v in s.append_to(Vec::new()) {
            if !m.contains(&v) {
                return Err(format!(
                    "missing value {} in m; s={:?}\nm={:?}",
                    v,
                    s.append_to(Vec::new()),
                    m
                ));
            }
        }

        // Additional check via s.has()
        for &v in m {
            if !s.has(v) {
                return Err(format!(
                    "missing value {} in s; s={:?}\nm={:?}",
                    v,
                    s.append_to(Vec::new()),
                    m
                ));
            }
        }

        // Extra check via s.for_each()
        let mut err = None;
        s.for_each(|part| {
            for &v in part {
                if !m.contains(&v) {
                    err = Some(format!("missing value {v} in m inside s.for_each"));
                    return false;
                }
            }
            true
        });
        match err {
            Some(e) => Err(e),
            None => Ok(()),
        }
    }

    // Port of Go TestSetBasicOps (one test per subtest items count).
    #[test]
    fn test_set_basic_ops_1() {
        test_set_basic_ops(1);
    }
    #[test]
    fn test_set_basic_ops_2() {
        test_set_basic_ops(2);
    }
    #[test]
    fn test_set_basic_ops_3() {
        test_set_basic_ops(3);
    }
    #[test]
    fn test_set_basic_ops_4() {
        test_set_basic_ops(4);
    }
    #[test]
    fn test_set_basic_ops_5() {
        test_set_basic_ops(5);
    }
    #[test]
    fn test_set_basic_ops_6() {
        test_set_basic_ops(6);
    }
    #[test]
    fn test_set_basic_ops_100() {
        test_set_basic_ops(100);
    }
    #[test]
    fn test_set_basic_ops_1000() {
        test_set_basic_ops(1000);
    }
    #[test]
    fn test_set_basic_ops_10000() {
        test_set_basic_ops(10_000);
    }
    #[test]
    fn test_set_basic_ops_100000() {
        test_set_basic_ops(100_000);
    }
    #[test]
    fn test_set_basic_ops_1000000() {
        test_set_basic_ops(1_000_000);
    }

    fn now_nanos() -> u64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time before Unix epoch")
            .as_nanos() as u64
    }

    fn test_set_basic_ops(items_count: usize) {
        let mut s = Set::default();

        let offset = now_nanos();

        // Verify operations on an empty set.
        // (Go verifies a nil *Set here; Rust has no nil, so the empty set is
        // used instead. Go's `sNil.SizeBytes() == 0` has no Rust equivalent
        // since an empty Set still occupies size_of::<Set>() bytes.)
        {
            let s_empty = Set::default();
            assert!(
                !s_empty.has(123),
                "empty set shouldn't contain any item; found 123"
            );
            assert_eq!(s_empty.len(), 0, "unexpected empty set len");
            let result = s_empty.clone().append_to(Vec::new());
            assert!(result.is_empty(), "empty set append_to must return empty");
            let buf = vec![1u64, 2, 3];
            let result = s_empty.clone().append_to(buf.clone());
            assert_eq!(result, buf, "empty set append_to(buf) must return buf");
            let mut s_copy = s_empty.clone();
            assert_eq!(s_copy.len(), 0, "unexpected s_copy.len() from empty set");
            s_copy.add(123);
            assert_eq!(
                s_copy.len(),
                1,
                "unexpected s_copy.len() after adding an item"
            );
            s_copy.add(123);
            assert_eq!(
                s_copy.len(),
                1,
                "unexpected s_copy.len() after adding an item twice"
            );
            assert!(s_copy.has(123), "s_copy must contain 123");
            s_copy.del(123);
            assert_eq!(
                s_copy.len(),
                0,
                "unexpected s_copy.len() after deleting the item"
            );
            s_copy.del(123);
            assert_eq!(
                s_copy.len(),
                0,
                "unexpected s_copy.len() after double deleting the item"
            );
        }

        // Verify forward Add
        let items_count = (items_count / 2) * 2;
        for i in 0..items_count / 2 {
            s.add(i as u64 + offset);
        }
        assert_eq!(
            s.len(),
            items_count / 2,
            "unexpected s.len() after forward add"
        );
        assert!(s.size_bytes() > 0, "s.size_bytes() must be greater than 0");

        // Verify backward Add
        for i in 0..items_count / 2 {
            s.add((items_count - i - 1) as u64 + offset);
        }
        assert_eq!(
            s.len(),
            items_count,
            "unexpected s.len() after backward add"
        );

        // Verify repeated Add
        for i in 0..items_count / 2 {
            s.add(i as u64 + offset);
        }
        assert_eq!(
            s.len(),
            items_count,
            "unexpected s.len() after repeated add"
        );

        // Verify Has on existing bits
        for i in 0..items_count {
            assert!(
                s.has(i as u64 + offset),
                "missing bit {}",
                i as u64 + offset
            );
        }

        // Verify Has on missing bits
        for i in items_count..2 * items_count {
            assert!(
                !s.has(i as u64 + offset),
                "unexpected bit found: {}",
                i as u64 + offset
            );
        }

        // Verify Clone and Equal
        let s_copy = s.clone();
        assert_eq!(s_copy.len(), items_count, "unexpected s_copy.len()");
        for i in 0..items_count {
            assert!(
                s_copy.has(i as u64 + offset),
                "missing bit {} on s_copy",
                i as u64 + offset
            );
        }
        assert!(s_copy.equal(&s), "s must equal to s_copy");
        assert!(s.equal(&s_copy), "s_copy must equal to s");
        if !s.is_empty() {
            let s_empty = Set::default();
            assert!(!s.equal(&s_empty), "s mustn't equal to s_empty");
            let mut s_new = s.clone();
            s_new.del(offset);
            assert!(!s_new.equal(&s), "s_new mustn't equal to s");
            assert!(!s.equal(&s_new), "s mustn't equal to s_new");
            s_new.add(offset - 123);
            assert!(!s_new.equal(&s), "s_new mustn't equal to s");
            assert!(!s.equal(&s_new), "s mustn't equal to s_new");
        }

        // Verify AppendTo
        let mut a = s.append_to(Vec::new());
        assert_eq!(
            a.len(),
            items_count,
            "unexpected len of exported array; array:\n{a:?}"
        );
        assert!(
            a.is_sorted(),
            "unsorted result returned from append_to: {a:?}"
        );
        let mut m: HashSet<u64> = HashSet::new();
        for &x in &a {
            m.insert(x);
        }
        for i in 0..items_count {
            assert!(
                m.contains(&(i as u64 + offset)),
                "missing bit {} in the exported bits",
                i as u64 + offset
            );
        }

        // Verify ForEach
        {
            let mut s = Set::default();
            let mut m: HashSet<u64> = HashSet::new();
            for i in 0..items_count {
                let v = i as u64 + offset;
                s.add(v);
                m.insert(v);
            }

            // Verify visiting all the items.
            s.for_each(|part| {
                for &v in part {
                    assert!(m.contains(&v), "unexpected value v={v} passed to for_each");
                    m.remove(&v);
                }
                true
            });
            assert!(m.is_empty(), "for_each didn't visit {} items", m.len());

            // Verify fast stop
            let mut calls = 0;
            s.for_each(|_| {
                calls += 1;
                false
            });
            if items_count > 0 {
                assert_eq!(
                    calls, 1,
                    "unexpected number of for_each callback calls; want 1"
                );
            }

            // Verify for_each on an empty set (Go: nil set).
            let s1 = Set::default();
            s1.for_each(|_| {
                panic!("callback shouldn't be called on empty set");
            });
        }

        // Verify union
        {
            const UNION_OFFSET: usize = 12345;
            let mut s1 = Set::default();
            let mut s2 = Set::default();
            for i in 0..items_count {
                s1.add(i as u64 + offset);
                s2.add(i as u64 + offset + UNION_OFFSET as u64);
            }
            s1.union(&s2);
            let mut expected_len = 2 * items_count;
            if items_count > UNION_OFFSET {
                expected_len = items_count + UNION_OFFSET;
            }
            assert_eq!(s1.len(), expected_len, "unexpected s1.len() after union");

            // Verify union on empty set.
            let mut s3 = Set::default();
            s3.union(&s1);
            let expected_len = s1.len();
            assert_eq!(
                s3.len(),
                expected_len,
                "unexpected s3.len() after union with empty set"
            );
            let s4 = Set::default();
            let expected_len = s3.len();
            s3.union(&s4);
            assert_eq!(
                s3.len(),
                expected_len,
                "unexpected s3.len() after union with empty set"
            );
        }

        // Verify union_may_own
        {
            const UNION_OFFSET: usize = 12345;
            let mut s1 = Set::default();
            let mut s2 = Set::default();
            for i in 0..items_count {
                s1.add(i as u64 + offset);
                s2.add(i as u64 + offset + UNION_OFFSET as u64);
            }
            s1.union_may_own(&s2);
            let mut expected_len = 2 * items_count;
            if items_count > UNION_OFFSET {
                expected_len = items_count + UNION_OFFSET;
            }
            assert_eq!(s1.len(), expected_len, "unexpected s1.len() after union");

            // Verify union on empty set.
            let mut s3 = Set::default();
            let expected_len = s1.len();
            s3.union_may_own(&s1);
            assert_eq!(
                s3.len(),
                expected_len,
                "unexpected s3.len() after union with empty set"
            );
            let s4 = Set::default();
            let expected_len = s3.len();
            s3.union_may_own(&s4);
            assert_eq!(
                s3.len(),
                expected_len,
                "unexpected s3.len() after union with empty set"
            );
        }

        // Verify intersect
        {
            // Verify s1.intersect(s2) and s2.intersect(s1)
            let mut s1 = Set::default();
            let mut s2 = Set::default();
            for &intersect_offset in &[123u64, 12345, (1 << 32) + 4343] {
                s1 = Set::default();
                s2 = Set::default();
                for i in 0..items_count {
                    s1.add(i as u64 + offset);
                    s2.add(i as u64 + offset + intersect_offset);
                }
                let mut expected_len = 0usize;
                if items_count as u64 > intersect_offset {
                    expected_len = (items_count as u64 - intersect_offset) as usize;
                }
                let mut s1_copy = s1.clone();
                s1_copy.intersect(&s2);
                assert_eq!(
                    s1_copy.len(),
                    expected_len,
                    "unexpected s1.len() after intersect"
                );
                s2.intersect(&s1);
                assert_eq!(
                    s2.len(),
                    expected_len,
                    "unexpected s2.len() after intersect"
                );
            }

            // Verify intersect on empty set.
            let s3 = Set::default();
            s2.intersect(&s3);
            let expected_len = 0;
            assert_eq!(
                s2.len(),
                expected_len,
                "unexpected s2.len() after intersect with empty set"
            );
            let mut s4 = Set::default();
            s4.intersect(&s1);
            assert_eq!(
                s4.len(),
                expected_len,
                "unexpected s4.len() after intersect with empty set"
            );
        }

        // Verify subtract
        {
            const SUBTRACT_OFFSET: usize = 12345;
            let mut s1 = Set::default();
            let mut s2 = Set::default();
            for i in 0..items_count {
                s1.add(i as u64 + offset);
                s2.add(i as u64 + offset + SUBTRACT_OFFSET as u64);
            }
            s1.subtract(&s2);
            let expected_len = items_count.min(SUBTRACT_OFFSET);
            assert_eq!(s1.len(), expected_len, "unexpected s1.len() after subtract");

            // Verify subtract from empty set.
            let mut s3 = Set::default();
            s3.subtract(&s2);
            assert_eq!(
                s3.len(),
                0,
                "unexpected s3.len() after subtract from empty set"
            );
        }

        // Verify Del
        let mut items_deleted = 0;
        for i in items_count / 2..items_count - items_count / 4 {
            s.del(i as u64 + offset);
            items_deleted += 1;
        }
        assert_eq!(
            s.len(),
            items_count - items_deleted,
            "unexpected s.len() after del"
        );
        a.clear();
        a = s.append_to(a);
        assert_eq!(
            a.len(),
            items_count - items_deleted,
            "unexpected len of exported array"
        );
        let mut m: HashSet<u64> = HashSet::new();
        for &x in &a {
            m.insert(x);
        }
        for i in 0..items_count {
            if i >= items_count / 2 && i < items_count - items_count / 4 {
                assert!(
                    !m.contains(&(i as u64 + offset)),
                    "unexpected bit found after deleting: {}",
                    i as u64 + offset
                );
            } else {
                assert!(
                    m.contains(&(i as u64 + offset)),
                    "missing bit {} in the exported bits after deleting",
                    i as u64 + offset
                );
            }
        }

        // Try Del for non-existing items
        for i in items_count / 2..items_count - items_count / 4 {
            s.del(i as u64 + offset);
            s.del(i as u64 + offset);
            s.del(i as u64 + offset + items_count as u64);
        }
        assert_eq!(
            s.len(),
            items_count - items_deleted,
            "unexpected s.len() after del for non-existing items"
        );

        // Verify s_copy has the original data
        assert_eq!(s_copy.len(), items_count, "unexpected s_copy.len()");
        for i in 0..items_count {
            assert!(
                s_copy.has(i as u64 + offset),
                "missing bit {} on s_copy",
                i as u64 + offset
            );
        }
    }

    // Port of Go TestSetSparseItems (one test per subtest items count).
    #[test]
    fn test_set_sparse_items_100() {
        test_set_sparse_items(100);
    }
    #[test]
    fn test_set_sparse_items_1000() {
        test_set_sparse_items(1000);
    }
    #[test]
    fn test_set_sparse_items_10000() {
        test_set_sparse_items(10_000);
    }

    fn test_set_sparse_items(items_count: usize) {
        let mut rng = StdRng::seed_from_u64(1);
        let mut s = Set::default();
        let mut m: HashSet<u64> = HashSet::new();
        for _ in 0..items_count {
            let x = rng.random::<u64>();
            s.add(x);
            m.insert(x);
        }
        assert_eq!(s.len(), m.len(), "unexpected len()");
        assert!(
            s.size_bytes() > 0,
            "size_bytes() must return value greater than 0"
        );

        // Check Has
        for &x in &m {
            assert!(s.has(x), "missing item {x}");
        }
        for i in 0..items_count {
            let x = i as u64;
            if m.contains(&x) {
                continue;
            }
            assert!(!s.has(x), "unexpected item found {x}");
        }

        // Check Clone
        let s_copy = s.clone();
        assert_eq!(s_copy.len(), m.len(), "unexpected s_copy.len()");
        for &x in &m {
            assert!(s_copy.has(x), "missing item {x} on s_copy");
        }

        // Check AppendTo
        let mut a = s.append_to(Vec::new());
        assert_eq!(a.len(), m.len(), "unexpected len for append_to result");
        assert!(
            a.is_sorted(),
            "unsorted result returned from append_to: {a:?}"
        );
        for &x in &a {
            assert!(
                m.contains(&x),
                "unexpected item found in append_to result: {x}"
            );
        }

        // Check Del
        for &x in &m {
            s.del(x);
            s.del(x);
            s.del(x.wrapping_add(1));
            s.del(x.wrapping_sub(1));
        }
        assert_eq!(s.len(), 0, "unexpected number of items left after del");
        a.clear();
        a = s.append_to(a);
        assert_eq!(
            a.len(),
            0,
            "unexpected number of items returned from append_to after del: {a:?}"
        );

        // Check items in s_copy
        assert_eq!(s_copy.len(), m.len(), "unexpected s_copy.len() after del");
        for &x in &m {
            assert!(s_copy.has(x), "missing item {x} on s_copy after del");
        }
    }

    // Port of Go TestAddMulti.
    #[test]
    fn test_add_multi() {
        let f = |a: &[u64]| {
            let mut s1 = Set::default();
            let mut s2 = Set::default();
            s1.add_multi(a);
            for &x in a {
                s2.add(x);
            }
            assert_eq!(
                s1.len(),
                s2.len(),
                "unexpected number of items in the set;\nset:\n{:?}",
                s1.append_to(Vec::new())
            );
            for &x in a {
                assert!(s1.has(x), "missing item {x} in the set");
            }
            let a1 = s1.append_to(Vec::new());
            let a2 = s2.append_to(Vec::new());
            assert_eq!(a1, a2, "unexpected items in the set");

            // Try removing and then adding again all the items via add_multi to s1.
            for &x in a {
                s1.del(x);
            }
            assert_eq!(
                s1.len(),
                0,
                "non-zero number of items left after deletion: {}",
                s1.len()
            );
            s1.add_multi(a);
            assert_eq!(
                s1.len(),
                s2.len(),
                "unexpected number of items in the reused set"
            );
            for &x in a {
                assert!(s1.has(x), "missing item {x} in the reused set");
            }
            let a1 = s1.append_to(Vec::new());
            let a2 = s2.append_to(Vec::new());
            assert_eq!(a1, a2, "unexpected items in the reused set");
        };
        f(&[]);
        f(&[1]);
        f(&[0, 1, 2, 3, 4, 5]);
        f(&[0, 1 << 16, 2 << 16, (2 << 16) + 1]);
        f(&[
            0,
            1 << 16,
            2 << 16,
            (2 << 16) + 1,
            1 << 32,
            2 << 32,
            (2 << 32) + 1,
        ]);

        let mut a: Vec<u64> = Vec::new();
        for i in 0..32000u64 {
            a.push(i);
        }
        f(&a);

        let mut a: Vec<u64> = Vec::new();
        for i in 0..32000u64 {
            a.push((1 << 16) + i);
        }
        f(&a);

        let mut a: Vec<u64> = Vec::new();
        for i in 0..100_000u64 {
            a.push((1 << 32) + i);
        }
        f(&a);
    }

    // Port of Go TestSubtract.
    #[test]
    fn test_subtract() {
        fn f(a: &mut Set, b: &mut Set, want: &mut Set) {
            let b_before = b.append_to(Vec::new());
            a.subtract(b);
            let b_after = b.append_to(Vec::new());
            let got_values = a.append_to(Vec::new());
            let want_values = want.append_to(Vec::new());
            assert_eq!(want_values, got_values, "unexpected a set");
            assert_eq!(b_before, b_after, "unexpected b set");
        }

        // Go's helper s(start, end, se...) with additional (start, end) pairs.
        fn s(ranges: &[(u64, u64)]) -> Set {
            let mut set = Set::default();
            for &(start, end) in ranges {
                for i in start..=end {
                    set.add(i);
                }
            }
            set
        }

        // - no overlap
        // - a values before b values
        // - len(a) > len(b)
        let mut a = s(&[(1, 500_000)]);
        let mut b = s(&[(500_001, 600_000)]);
        let mut want = s(&[(1, 500_000)]);
        f(&mut a, &mut b, &mut want);

        // - no overlap
        // - a values after b values
        // - len(a) > len(b)
        let mut a = s(&[(500_001, 1_000_000)]);
        let mut b = s(&[(400_000, 500_000)]);
        let mut want = s(&[(500_001, 1_000_000)]);
        f(&mut a, &mut b, &mut want);

        // - no overlap
        // - a values before b values
        // - len(a) < len(b)
        let mut a = s(&[(400_000, 500_000)]);
        let mut b = s(&[(500_001, 1_000_000)]);
        let mut want = s(&[(400_000, 500_000)]);
        f(&mut a, &mut b, &mut want);

        // - no overlap
        // - a values after b values
        // - len(a) < len(b)
        let mut a = s(&[(500_001, 600_000)]);
        let mut b = s(&[(1, 500_000)]);
        let mut want = s(&[(500_001, 600_000)]);
        f(&mut a, &mut b, &mut want);

        // - overlap on the left side
        // - len(a) > len(b)
        let mut a = s(&[(500_000, 1_000_000)]);
        let mut b = s(&[(400_000, 600_000)]);
        let mut want = s(&[(600_001, 1_000_000)]);
        f(&mut a, &mut b, &mut want);

        // - overlap on the right side
        // - len(a) > len(b)
        let mut a = s(&[(1, 500_000)]);
        let mut b = s(&[(400_001, 600_000)]);
        let mut want = s(&[(1, 400_000)]);
        f(&mut a, &mut b, &mut want);

        // - overlap on the left side
        // - len(a) < len(b)
        let mut a = s(&[(400_000, 600_000)]);
        let mut b = s(&[(500_001, 1_000_000)]);
        let mut want = s(&[(400_000, 500_000)]);
        f(&mut a, &mut b, &mut want);

        // - overlap on the right side
        // - len(a) < len(b)
        let mut a = s(&[(400_000, 600_000)]);
        let mut b = s(&[(1, 500_000)]);
        let mut want = s(&[(500_001, 600_000)]);
        f(&mut a, &mut b, &mut want);

        // same
        let mut a = s(&[(1, 500_000)]);
        let mut b = s(&[(1, 500_000)]);
        let mut want = Set::default();
        f(&mut a, &mut b, &mut want);

        // b is a subset of a
        let mut a = s(&[(1, 500_000)]);
        let mut b = s(&[(100_001, 400_000)]);
        let mut want = s(&[(1, 100_000), (400_001, 500_000)]);
        f(&mut a, &mut b, &mut want);

        // a is a subset of b
        let mut a = s(&[(100_001, 400_000)]);
        let mut b = s(&[(1, 500_000)]);
        let mut want = Set::default();
        f(&mut a, &mut b, &mut want);

        // a with intervals
        let mut a = s(&[(1, 200_000), (400_000, 500_000)]);
        let mut b = s(&[(150_001, 450_000)]);
        let mut want = s(&[(1, 150_000), (450_001, 500_000)]);
        f(&mut a, &mut b, &mut want);

        // b with intervals
        let mut a = s(&[(1, 500_000)]);
        let mut b = s(&[(200_001, 300_000), (400_001, 500_000)]);
        let mut want = s(&[(1, 200_000), (300_001, 400_000)]);
        f(&mut a, &mut b, &mut want);

        // subtract more than once.
        let mut a = s(&[(1, 500_000)]);
        let mut b1 = s(&[(100_001, 200_000)]);
        let mut want1 = s(&[(1, 100_000), (200_001, 500_000)]);
        let mut b2 = s(&[(300_001, 400_000)]);
        let mut want2 = s(&[(1, 100_000), (200_001, 300_000), (400_001, 500_000)]);
        f(&mut a, &mut b1, &mut want1);
        f(&mut a, &mut b2, &mut want2);
    }

    // Port of Go TestUnmarshal.
    #[test]
    fn test_unmarshal() {
        let n = 100_000u64;
        let mut src = vec![0u8; ((n + 1) * 8) as usize + 10];
        src[..8].copy_from_slice(&n.to_be_bytes());
        let mut want = Set::default();
        for i in 0..n {
            let pos = ((i + 1) * 8) as usize;
            src[pos..pos + 8].copy_from_slice(&i.to_be_bytes());
            want.add(i);
        }

        let (got, got_tail) = match Set::unmarshal(&src) {
            Ok(v) => v,
            Err(err) => panic!("unexpected error: {err}"),
        };
        let mut got = got;
        assert!(
            got.equal(&want),
            "unexpected set; want {:?}; got {:?}",
            want.append_to(Vec::new()),
            got.append_to(Vec::new())
        );
        let want_tail = vec![0u8; 10];
        assert_eq!(want_tail.as_slice(), got_tail, "unexpected tail bytes");
    }

    // Port of Go TestUnmarshal_zeroLenSet.
    #[test]
    fn test_unmarshal_zero_len_set() {
        let src = vec![0u8; 8];
        let want = Set::default();
        let (got, got_tail) = match Set::unmarshal(&src) {
            Ok(v) => v,
            Err(err) => panic!("unexpected error: {err}"),
        };
        assert!(got.equal(&want), "unexpected set");
        let want_tail: &[u8] = &[];
        assert_eq!(want_tail, got_tail, "unexpected tail bytes");
    }

    // Port of Go TestUnmarshal_tooShortToIncludeSetLen.
    #[test]
    fn test_unmarshal_too_short_to_include_set_len() {
        let src = vec![0u8; 7]; // the set length occupies 8 bytes.
        let result = Set::unmarshal(&src);
        assert!(result.is_err(), "expected error but got none");
    }

    // Port of Go TestUnmarshal_numElementsLessThanLen.
    #[test]
    fn test_unmarshal_num_elements_less_than_len() {
        let n = 10u64;
        let mut src = vec![0u8; (n * 8) as usize]; // contains only 9 elements instead of 10.
        src[..8].copy_from_slice(&n.to_be_bytes());
        for i in 0..n - 1 {
            let pos = ((i + 1) * 8) as usize;
            src[pos..pos + 8].copy_from_slice(&i.to_be_bytes());
        }

        let result = Set::unmarshal(&src);
        assert!(result.is_err(), "expected error but got none");
    }

    // Port of Go TestMarshal_emptyDst.
    #[test]
    fn test_marshal_empty_dst() {
        let n = 100_000u64;
        let mut want = vec![0u8; ((n + 1) * 8) as usize];
        want[..8].copy_from_slice(&n.to_be_bytes());
        let mut s = Set::default();
        for i in 0..n {
            let pos = ((i + 1) * 8) as usize;
            want[pos..pos + 8].copy_from_slice(&i.to_be_bytes());
            s.add(i);
        }

        let got = s.marshal(Vec::new());
        assert_eq!(want, got, "unexpected bytes");
    }

    // Port of Go TestMarshal_nonEmptyDst.
    #[test]
    fn test_marshal_non_empty_dst() {
        let n = 100_000u64;
        let mut got = vec![0u8; 10];
        let mut want = vec![0u8; 10 + ((n + 1) * 8) as usize];
        for i in 0..10 {
            got[i] = i as u8;
            want[i] = i as u8;
        }
        want[10..18].copy_from_slice(&n.to_be_bytes());
        let mut s = Set::default();
        for i in 0..n {
            let pos = 10 + ((i + 1) * 8) as usize;
            want[pos..pos + 8].copy_from_slice(&i.to_be_bytes());
            s.add(i);
        }

        let got = s.marshal(got);
        assert_eq!(want, got, "unexpected bytes");
    }
}
